version: '3'

services:
  datadog-mock:
    build:
      context: .
      dockerfile: Dockerfile
    image: nikscorp/datadog-mock
    container_name: datadog-mock
    logging:
        driver: json-file
        options:
            max-size: "10m"
            max-file: "5"
    restart: always
    ports:
        - "8125:8125/udp"
